/**
 * BTS (Bubble Tea Speaking) 레벨별 회화/대화 문장 데이터
 * 망고아이 BTS 1~34 교재에서 추출한 원어민 발음 연습 문장
 */
const BTS_SENTENCES = {
  "BTS 1": {
    title: "My School",
    topic: "Welcome to School / School Stuff / My Classroom",
    sentences: [
      "Hi, Ken! How are you?",
      "How are you, Karen?",
      "Well, I am okay. Are you excited?",
      "School! Our new teacher is a woman.",
      "Is she scary?",
      "No, she is not. She is so kind!",
      "Wow! That is good.",
      "Let's go to school now!",
      "Okay. Let's go!",
      "I am a teacher.",
      "I am a student.",
      "She is a girl.",
      "He is a boy.",
      "She is a woman.",
      "He is a man.",
      "Is she a girl? Yes, she is.",
      "Is he a boy? Yes, he is.",
      "Nice to meet you.",
      "How are you? I am fine, thank you.",
      "What is it? It is a notebook.",
      "What is it? It is a ruler.",
      "Does she have a pen?",
      "Do they have scissors?",
      "What is in the backpack?",
      "Hi Jane, how are you? I'm okay. What about you?",
      "I'm fine too. Thanks! Your backpack looks nice.",
      "This is my desk.",
      "That is the whiteboard.",
      "Where is the clock? It is on the wall."
    ]
  },
  "BTS 2": {
    title: "Shapes and Colors",
    topic: "Shapes / Colors / Describing Objects",
    sentences: [
      "What shape is it?",
      "It is a circle.",
      "It is a square.",
      "It is a triangle.",
      "It is a rectangle.",
      "It is a star.",
      "What color is the rose? The rose is red.",
      "The teddy bear is brown.",
      "The heart is yellow.",
      "The toy car is purple.",
      "The balloon is green.",
      "What color is it? It is blue.",
      "It is a red heart.",
      "What shape is the present?",
      "The present is a rectangle.",
      "What color is the balloon? The balloon is orange.",
      "I like the color pink.",
      "My favorite color is blue.",
      "This is a big circle.",
      "That is a small triangle."
    ]
  },
  "BTS 3": {
    title: "My Family",
    topic: "Family Members / Descriptions",
    sentences: [
      "Who is she? She is my mother.",
      "Who is he? He is my father.",
      "This is my family.",
      "They are my father, my mother, my two brothers, and me!",
      "This is my father. He has black hair.",
      "This is my mother. She is beautiful.",
      "He is my brother. He is tall.",
      "She is my sister. She is kind.",
      "This is my grandmother.",
      "That is my grandfather.",
      "How many people are in your family?",
      "There are five people in my family.",
      "I love my family.",
      "My brother is older than me.",
      "My sister is younger than me.",
      "Do you have any brothers or sisters?",
      "Yes, I have one brother and one sister.",
      "My father is a doctor.",
      "My mother is a nurse."
    ]
  },
  "BTS 4": {
    title: "Food and Meals",
    topic: "Food / Meals / Likes and Dislikes",
    sentences: [
      "What is it? It is an apple.",
      "What is it? It is an orange.",
      "Does she like cookies? Yes, she likes cookies.",
      "Do you like pizza? Yes, I do.",
      "I like ice cream.",
      "I don't like vegetables.",
      "What is your favorite food?",
      "My favorite food is spaghetti.",
      "What did you eat for breakfast?",
      "I had cereal and milk for breakfast.",
      "What did you eat for lunch?",
      "I had a sandwich for lunch.",
      "What will you eat for dinner?",
      "I will have rice and soup for dinner.",
      "Are you hungry? Yes, I am very hungry.",
      "Would you like some water?",
      "Yes, please. Thank you.",
      "This is delicious!",
      "Can I have some more, please?"
    ]
  },
  "BTS 5": {
    title: "Days, Seasons, Time",
    topic: "Days of the Week / Seasons / Telling Time",
    sentences: [
      "How many days are there in a week?",
      "There are seven days in a week.",
      "What day is it today? Today is Monday.",
      "Tomorrow is Tuesday.",
      "Yesterday was Sunday.",
      "What is your favorite day of the week?",
      "My favorite day is Saturday.",
      "What season is it? It is spring.",
      "It is summer. It is very hot.",
      "It is fall. The leaves are changing colors.",
      "It is winter. It is very cold.",
      "What time is it?",
      "It is three o'clock.",
      "It is half past four.",
      "What time do you wake up?",
      "I wake up at seven o'clock.",
      "What time do you go to school?",
      "I go to school at eight thirty.",
      "What time do you go to bed?",
      "I go to bed at nine o'clock."
    ]
  },
  "BTS 6": {
    title: "Bedroom and Living Room",
    topic: "Furniture / Rooms / Prepositions",
    sentences: [
      "What is it? It is a bed.",
      "What color is your blanket?",
      "My blanket is blue.",
      "Where is the lamp? The lamp is on the table.",
      "Where are the books? The books are on the shelf.",
      "The women are behind the chair.",
      "The cat is under the bed.",
      "The ball is next to the door.",
      "This is my bedroom.",
      "That is the living room.",
      "There is a sofa in the living room.",
      "There are two pillows on the sofa.",
      "Where is the remote control?",
      "It is on the coffee table.",
      "The television is in front of the sofa.",
      "I like to read books in my bedroom.",
      "My family watches TV in the living room.",
      "Where do you do your homework?",
      "I do my homework at my desk."
    ]
  },
  "BTS 7": {
    title: "My Head, Face, Body",
    topic: "Body Parts / Descriptions",
    sentences: [
      "What is this? This is my head.",
      "These are my eyes.",
      "This is my nose.",
      "These are my ears.",
      "This is my mouth.",
      "These are my teeth.",
      "How many fingers do you have?",
      "I have ten fingers.",
      "Can you show me your forehead?",
      "How many eyes does a spider have?",
      "What do you see with? I see with my eyes.",
      "What do you hear with? I hear with my ears.",
      "I use my nose for smelling.",
      "I bite apples with my teeth.",
      "He has two arms and two legs.",
      "She has long hair.",
      "Touch your head. Touch your shoulders.",
      "Point to your knees. Point to your toes.",
      "How many chests does he have? He has one chest.",
      "The dog has four legs."
    ]
  },
  "BTS 8": {
    title: "Playing Soccer",
    topic: "Sports / Actions / Present Continuous",
    sentences: [
      "What are you doing? I am playing soccer.",
      "He is kicking the ball.",
      "She is running fast.",
      "They are playing basketball.",
      "He kicks the ball with his foot.",
      "She throws the ball with her hand.",
      "They play basketball with their hands.",
      "What is he doing? He is hitting the ball.",
      "How does he play baseball?",
      "He hits the ball with his bat.",
      "Is she playing badminton? Yes, she is.",
      "Are they swimming? No, they are not.",
      "I like to play soccer after school.",
      "Do you want to play with me?",
      "Let's play together!",
      "What sport do you like?",
      "My favorite sport is soccer.",
      "She is jumping rope.",
      "He is riding a bicycle.",
      "They are doing exercises."
    ]
  },
  "BTS 9": {
    title: "Night and Day, Time",
    topic: "Daily Routines / Time / Day and Night",
    sentences: [
      "When can you see the sun?",
      "When can you see the moon?",
      "The sun rises in the morning.",
      "In the afternoon the sun is high in the sky.",
      "The sun sets in the evening.",
      "The moon comes out at night.",
      "What do you do in the morning?",
      "I brush my teeth in the morning.",
      "I eat breakfast at seven thirty.",
      "I go to school at eight o'clock.",
      "What do you do in the afternoon?",
      "I study at school in the afternoon.",
      "What do you do in the evening?",
      "I do my homework in the evening.",
      "I take a shower before bed.",
      "I go to sleep at nine o'clock.",
      "Do you wake up early?",
      "Yes, I wake up at six thirty.",
      "Good morning! How did you sleep?",
      "Good night! Sweet dreams!"
    ]
  },
  "BTS 10": {
    title: "Weather",
    topic: "Weather / Seasons / Activities",
    sentences: [
      "What's the weather like today?",
      "It's sunny today. I love it!",
      "It's cloudy outside.",
      "It's raining. Don't forget your umbrella.",
      "It's snowing! Let's build a snowman.",
      "It's windy today. Hold on to your hat!",
      "It's very hot. Let's get some ice cream.",
      "It's very cold. Put on your jacket.",
      "How's the weather in your city?",
      "In summer, it is usually hot and humid.",
      "In winter, it is cold and sometimes snowy.",
      "What do you do when it rains?",
      "I stay inside and read a book.",
      "What do you do on a sunny day?",
      "I go to the park and play outside.",
      "Do you like rainy days?",
      "I prefer sunny days.",
      "The temperature is thirty degrees today.",
      "Is it going to rain tomorrow?",
      "I heard it will be sunny tomorrow."
    ]
  },
  "BTS 11": {
    title: "Stores",
    topic: "Shopping / Stores / Buying Things",
    sentences: [
      "What do they have at the store?",
      "They have many clothes.",
      "What does this store sell?",
      "It sells shoes and bags.",
      "Do you want to go to the clothing store?",
      "How much is this shirt?",
      "It is fifteen dollars.",
      "Can I try this on?",
      "Sure, the fitting room is over there.",
      "This is too big. Do you have a smaller size?",
      "I would like to buy this, please.",
      "Do you have it in a different color?",
      "Where is the bookstore?",
      "It is next to the bakery.",
      "Let's go to the toy store!",
      "How much are these shoes?",
      "They are on sale for twenty dollars.",
      "Do you have any change?",
      "Here is your receipt. Thank you!",
      "Have a nice day!"
    ]
  },
  "BTS 12": {
    title: "Jobs, Going to Work",
    topic: "Occupations / Workplaces",
    sentences: [
      "Who is she? She is a teacher.",
      "Where does she work? She works at a school.",
      "He is a doctor. He works at a hospital.",
      "She is a firefighter. She is very brave.",
      "He is a police officer. He keeps us safe.",
      "What do you want to be when you grow up?",
      "I want to be a scientist.",
      "My father is an engineer.",
      "My mother is a nurse.",
      "A chef works in a restaurant.",
      "A pilot flies an airplane.",
      "A farmer works on a farm.",
      "What does a teacher do?",
      "A teacher teaches students at school.",
      "What does a doctor do?",
      "A doctor helps sick people get better.",
      "How does your father go to work?",
      "He takes the subway to work.",
      "She drives a car to work.",
      "I want to help people when I grow up."
    ]
  },
  "BTS 13": {
    title: "Past Tense",
    topic: "Yesterday and Today / Past Actions",
    sentences: [
      "What is the man doing now? He is playing basketball.",
      "What did the man play earlier? He played basketball.",
      "What is Nadia doing right now? She is doing her homework.",
      "What did Nadia do last night? She did her homework.",
      "What are they playing now? They are playing tag.",
      "What did they play yesterday? They played tag.",
      "Did you play with your friends yesterday?",
      "Did you eat dinner last night?",
      "Did you do your homework?",
      "Who did you visit? I visited my grandparents.",
      "When did you visit them? I visited them last week.",
      "How did you get there? We rode the subway.",
      "I went to the park yesterday.",
      "She watched a movie last night.",
      "They had a pillow fight last night.",
      "We played games yesterday.",
      "He studied English last weekend.",
      "Did you go swimming yesterday?",
      "Where did you go? I went to the library.",
      "What did you do there? I read some books."
    ]
  },
  "BTS 14": {
    title: "Future Tense",
    topic: "Plans / Tomorrow / Future Actions",
    sentences: [
      "What will you do tomorrow?",
      "I will go to school tomorrow.",
      "I will not do my work tomorrow. I will do it now!",
      "What will he eat tomorrow? He will eat spaghetti.",
      "She will not play video games tomorrow.",
      "What will he do this weekend?",
      "He will play soccer this weekend.",
      "Do you think he will win?",
      "Who is going to be sixteen years old on Saturday?",
      "When will the party start?",
      "What will everyone eat at the party?",
      "Who will be there?",
      "I will study hard for the test.",
      "We will go to the beach this summer.",
      "She will visit her grandmother next week.",
      "They will have a big dinner tonight.",
      "Will you come to my birthday party?",
      "Yes, I will be there!",
      "What are you going to do after school?",
      "I am going to play with my friends."
    ]
  },
  "BTS 15": {
    title: "True Stories, Fiction",
    topic: "Stories / Facts / Fiction",
    sentences: [
      "This is a true story.",
      "That story is fiction. It is not real.",
      "Do you like reading stories?",
      "What is your favorite book?",
      "Is this story true or fiction?",
      "Once upon a time, there was a brave knight.",
      "The princess lived in a big castle.",
      "The dragon was very scary.",
      "In the end, they lived happily ever after.",
      "Have you ever read a biography?",
      "A biography is a true story about a real person.",
      "Fiction stories come from the writer's imagination.",
      "What kind of stories do you like?",
      "I like adventure stories.",
      "She prefers mystery stories.",
      "Can you tell me a story?",
      "Let me tell you about what happened.",
      "This really happened to me last year.",
      "The most interesting part of the story was the ending.",
      "Who is your favorite character in the story?"
    ]
  },
  "BTS 16": {
    title: "Choices, Inventions, Promises",
    topic: "Making Choices / Inventions / Keeping Promises",
    sentences: [
      "Oh no! There's a monster! What will he do?",
      "He will fight it, and he will go to his palace.",
      "There's a stranger. What will they do?",
      "They will not talk to the stranger.",
      "What would you choose?",
      "I would choose the blue one.",
      "If you could have any superpower, what would it be?",
      "I would choose to fly.",
      "What is the most important invention?",
      "I think the telephone is very important.",
      "Who invented the light bulb?",
      "Thomas Edison invented the light bulb.",
      "I promise I will do my best.",
      "Can you keep a promise?",
      "Yes, I always keep my promises.",
      "She promised to help me with my homework.",
      "He made a promise to be on time.",
      "I promise to study harder this year.",
      "What do you promise to do better?",
      "I promise to be kind to everyone."
    ]
  },
  "BTS 17": {
    title: "Hobbies and Activities",
    topic: "Hobbies / Directions / Comparative Adjectives",
    sentences: [
      "What is your hobby?",
      "My hobby is taking pictures.",
      "I think taking pictures is fun while painting is relaxing.",
      "What do you need to play baduk?",
      "To play baduk, I need a board and a set of stones.",
      "Which hobby do you enjoy the most?",
      "I enjoy playing the piano the most.",
      "Turn left at the corner.",
      "Go straight for two blocks.",
      "Turn right at the traffic light.",
      "The library is across from the school.",
      "This building is taller than that one.",
      "English is more interesting than math.",
      "She is faster than her brother.",
      "Which is bigger, an elephant or a mouse?",
      "An elephant is much bigger than a mouse.",
      "This book is more exciting than that one.",
      "Who is taller, you or your friend?",
      "I am taller than my friend.",
      "What activity do you do after school?"
    ]
  },
  "BTS 18": {
    title: "Animals",
    topic: "Animals / Habitats / Pets",
    sentences: [
      "A desert is a very dry place.",
      "Monkeys usually live in the forest.",
      "I think they are playful and smart.",
      "Can monkeys be kept as pets?",
      "What is your favorite animal?",
      "My favorite animal is a dog.",
      "Where do polar bears live?",
      "Polar bears live in the Arctic.",
      "Lions are called the king of the jungle.",
      "Fish live in water.",
      "Birds can fly in the sky.",
      "Do you have a pet?",
      "Yes, I have a pet cat.",
      "What does your pet eat?",
      "My cat eats cat food and fish.",
      "How do you take care of your pet?",
      "I feed my pet every day.",
      "Some animals are endangered.",
      "We should protect wild animals.",
      "The zoo has many different animals."
    ]
  },
  "BTS 19": {
    title: "Jobs, Skills and Training",
    topic: "Careers / Skills / Training",
    sentences: [
      "What do you want to be in the future?",
      "I want to be an architect.",
      "A firefighter saves people from fires.",
      "An entrepreneur starts their own business.",
      "A counselor helps people with their problems.",
      "What skills do you need for that job?",
      "You need to study hard and practice a lot.",
      "She wants to be an artist when she grows up.",
      "He is training to be a professional athlete.",
      "What subject are you good at?",
      "I am good at math and science.",
      "I want to teach art to children.",
      "How long do you have to go to school for that job?",
      "You have to study for at least four years.",
      "Practice makes perfect.",
      "Never give up on your dreams.",
      "What job do you think is the most interesting?",
      "I think being a pilot is very exciting.",
      "Do you like working with people or with computers?",
      "I prefer working with people."
    ]
  },
  "BTS 20": {
    title: "Food and Restaurants",
    topic: "Restaurants / Taste / Special Orders",
    sentences: [
      "What would you like to order?",
      "I would like to have a hamburger, please.",
      "Would you like something to drink?",
      "Yes, I'll have an orange juice.",
      "How does it taste?",
      "It tastes delicious!",
      "This is too salty.",
      "This is too sweet.",
      "Can I have the menu, please?",
      "Are you ready to order?",
      "I'll have the pasta, please.",
      "Would you like any dessert?",
      "No, thank you. Just the check, please.",
      "How much is the total?",
      "The total is twenty-five dollars.",
      "Here you go. Keep the change.",
      "Thank you! Come again!",
      "This soup is very hot. Be careful.",
      "The food here is really good.",
      "I would like to make a special order, please."
    ]
  },
  "BTS 21": {
    title: "Holidays",
    topic: "Holidays / Celebrations / Traditions",
    sentences: [
      "What is your favorite holiday?",
      "My favorite holiday is Christmas.",
      "What do you do on that holiday?",
      "We meet our relatives and have a big dinner.",
      "Do you decorate your house for the holidays?",
      "Yes, we put up a Christmas tree.",
      "What holidays does your country celebrate?",
      "We celebrate New Year's Day and Chuseok.",
      "On Halloween, children wear costumes.",
      "They go trick-or-treating in the neighborhood.",
      "Thanksgiving is a time to be grateful.",
      "What are you thankful for?",
      "I am thankful for my family and friends.",
      "Do you give gifts on birthdays?",
      "Yes, I always give presents to my friends.",
      "Happy holidays! Have a wonderful time!",
      "How do you celebrate the New Year?",
      "We watch fireworks at midnight.",
      "Do you attend any festivals?",
      "Yes, I love going to the lantern festival."
    ]
  },
  "BTS 22": {
    title: "My Body, Health",
    topic: "Body / Sickness / Staying Healthy",
    sentences: [
      "How are you feeling today?",
      "I don't feel well. I have a headache.",
      "You should see a doctor.",
      "I have a stomachache.",
      "She has a fever and a sore throat.",
      "I need to take some medicine.",
      "Get some rest and drink lots of water.",
      "How do you stay healthy?",
      "I exercise every day.",
      "I eat fruits and vegetables.",
      "You should wash your hands often.",
      "Don't forget to brush your teeth.",
      "Getting enough sleep is very important.",
      "How many hours do you sleep?",
      "I sleep about eight hours every night.",
      "She went to the hospital because she was sick.",
      "The doctor said I need to rest for two days.",
      "I feel much better now. Thank you.",
      "An apple a day keeps the doctor away.",
      "Stay healthy and take care of yourself."
    ]
  },
  "BTS 23": {
    title: "TV, News, Commercials",
    topic: "Television / News / Advertisements",
    sentences: [
      "What's on TV tonight?",
      "There is a documentary about animals.",
      "I like watching cartoons.",
      "My favorite show is on at eight o'clock.",
      "Did you watch the news today?",
      "Yes, I saw an interesting report about technology.",
      "What kind of TV shows do you like?",
      "I like comedy shows. They make me laugh.",
      "How many hours of TV do you watch a day?",
      "I watch about one hour of TV a day.",
      "Commercials try to make you buy things.",
      "Do you believe everything you see on TV?",
      "No, you should think carefully about what you see.",
      "The news reporter said it will rain tomorrow.",
      "Have you ever been on TV?",
      "No, but I would like to be on a game show.",
      "Too much TV is not good for your eyes.",
      "Reading a book is better than watching TV.",
      "What did you learn from the news today?",
      "I learned about a new discovery in science."
    ]
  },
  "BTS 24": {
    title: "Fantasy Worlds",
    topic: "Fantasy / Imagination / If I Were a Millionaire",
    sentences: [
      "If you could have any magical power, what would it be?",
      "I would choose to be invisible.",
      "If I were a millionaire, I would travel the world.",
      "What would you buy if you had a million dollars?",
      "I would buy a big house for my family.",
      "If I could fly, I would visit every country.",
      "What if you could talk to animals?",
      "That would be amazing! I would talk to my dog.",
      "If I were a superhero, I would save everyone.",
      "Imagine you could go anywhere in the world.",
      "Where would you go?",
      "I would go to Paris to see the Eiffel Tower.",
      "If you could meet anyone, who would it be?",
      "I would meet my favorite scientist.",
      "What would you do if you could stop time?",
      "I would use the extra time to study and play.",
      "If dragons were real, would you be scared?",
      "No, I would try to make friends with one!",
      "Use your imagination to create something new.",
      "Anything is possible if you believe in yourself."
    ]
  },
  "BTS 25": {
    title: "Great Inventions",
    topic: "Inventions / Communication / Technology",
    sentences: [
      "How do we communicate with each other?",
      "Hey, look! I have a new smartphone!",
      "That's nice! What features does it have?",
      "It has tons of features!",
      "Can you call people with that phone?",
      "The telephone was an important invention.",
      "Alexander Graham Bell invented the telephone.",
      "I use my smartphone to do homework and play games.",
      "I can use it to access the internet.",
      "I can communicate with my friends through online chatting.",
      "I don't know what I would do without my smartphone.",
      "Do you have a washing machine at home?",
      "Which one is more efficient to use? Why?",
      "What do you usually cook with the microwave?",
      "The zipper was invented in the late eighteen hundreds.",
      "People liked zippers because they were faster and easier to use than buttons.",
      "I think the stapler is a very useful invention.",
      "Scissors are also very helpful. Students use them to cut things.",
      "All inventions are useful; people just need to use them properly.",
      "What do you think is the greatest invention ever?"
    ]
  },
  "BTS 26": {
    title: "Animals in their Habitats",
    topic: "Habitats / Adaptation / Natural Resources",
    sentences: [
      "Tropical areas have warm climates all year.",
      "Polar areas have cold climates.",
      "Temperate areas have hot summers and cold winters.",
      "Camels live in the desert.",
      "They can live for one week without water.",
      "They have special fur that stops them from getting too hot.",
      "Could they live in a different habitat? Why or why not?",
      "These are all the ways that the cuttlefish has adapted to its environment.",
      "Resources are things people need to live their lives.",
      "Natural resources come from nature.",
      "What natural resources can you think of?",
      "Most people use lots of water to cook food.",
      "How much water do you use every day?",
      "Do you have a dishwasher in your home?",
      "We should protect our environment.",
      "What can you do to help the earth?",
      "Would you please stop littering?",
      "Reduce, reuse, and recycle.",
      "We raise fish so we don't have to catch them from the ocean.",
      "Look at the people doing bad things to the earth. Politely tell them to stop."
    ]
  },
  "BTS 27": {
    title: "Fashion",
    topic: "Clothes / Style / Materials",
    sentences: [
      "A person's style is the way they dress and how they look.",
      "Cotton is used to make many different clothes.",
      "Many t-shirts, sweatshirts, and socks are made of cotton.",
      "Cotton clothes can be casual and cheap or fancy and expensive.",
      "Are many of your clothes made of cotton?",
      "The sweater she wears is made of wool.",
      "Sometimes I don't need to look fashionable.",
      "When I go to English class, I want to look nice.",
      "I have a few new sweaters and skirts that I think are very fashionable.",
      "My friends said that my new skirt was pretty and I felt very happy.",
      "I like it when my clothes make me feel good.",
      "My mom says that money can't always buy happiness.",
      "I think she's right.",
      "Polka dots have been popular for about one hundred years.",
      "Many people think they look fashionable and cute.",
      "What is your favorite outfit?",
      "Do you care about fashion?",
      "What accessories do you usually wear?",
      "How would you describe your style?",
      "I prefer comfortable clothes."
    ]
  },
  "BTS 28": {
    title: "Travel in Asia",
    topic: "Travel / Vacation / Tourist Attractions",
    sentences: [
      "People go to historical places because they are old and important.",
      "Many museums are also historical tourist attractions.",
      "What kinds of vacation has your family gone on?",
      "Where do you want to go on your next vacation?",
      "Do you always agree with your family about where to go?",
      "What activity can you probably do in Shibuya?",
      "Leon's parents like camping, but he really doesn't.",
      "Sleeping on the ground is uncomfortable for him.",
      "Leon wishes to go somewhere different on their vacation.",
      "He would really like to go to a beach resort.",
      "He could swim in the water and experience water sports like surfing.",
      "It would be best for them to stay in a hotel.",
      "All of them could take hot showers and sleep comfortably.",
      "Have you ever traveled to another country?",
      "Which country would you like to visit?",
      "I would like to visit Japan someday.",
      "What is the most interesting place you have been to?",
      "I went to Jeju Island last summer.",
      "It was a wonderful experience.",
      "Traveling is a great way to learn about different cultures."
    ]
  },
  "BTS 29": {
    title: "Heroes, Money, Friends",
    topic: "Role Models / Saving Money / Friendship",
    sentences: [
      "Do you admire any famous people? Why?",
      "I think it's important to have role models.",
      "My two personal heroes are Thomas Edison and Tiger Woods.",
      "Thomas Edison was an American inventor and businessman.",
      "He developed many devices, including the electric light.",
      "I can't imagine our house without lights.",
      "I admire him so much.",
      "When you can buy a nice thing for a very cheap price, it's a bargain.",
      "What is the best bargain you have ever found?",
      "I think I am a very friendly and outgoing person.",
      "I have lots of friends from school.",
      "Having fun with my friends is usually the best part of my day.",
      "I think one way to make people like you is to be generous.",
      "I always try to help my friends.",
      "She was very grateful and now we are closer friends.",
      "I strongly believe that I can make lots of friends by being generous.",
      "A true friend is always there for you.",
      "Friends help each other in difficult times.",
      "How many close friends do you have?",
      "What makes someone a good friend?"
    ]
  },
  "BTS 30": {
    title: "Living Abroad, Career",
    topic: "Living Abroad / Free Time / Career / Space",
    sentences: [
      "Do you want to live abroad? Why or why not?",
      "In my free time, it's very important to get a good workout.",
      "I prefer activities like riding my mountain bike or lifting weights.",
      "Working out keeps my body strong and helps me stay focused.",
      "It helps me get a good night's sleep.",
      "Math is my best subject in school.",
      "My teacher tells me that I have a natural talent for mathematics.",
      "I see numbers as a language, and I learn it very quickly.",
      "I really enjoy learning about computers.",
      "I really hope I can use math in my career.",
      "I think I could be a scientist, an engineer, or a computer programmer.",
      "Then I can have a satisfying career doing something I am really good at.",
      "What kind of training do you need for this job?",
      "How many years do you have to go to school?",
      "What does the job involve?",
      "Have you ever thought about living in another country?",
      "What would you miss most about Korea?",
      "I would miss my family and Korean food.",
      "What career are you interested in?",
      "I am interested in becoming a doctor."
    ]
  },
  "BTS 31": {
    title: "Movies, Pets, School Uniforms",
    topic: "Movies / Pets / Uniforms / Leadership",
    sentences: [
      "Do you like to go to the movies?",
      "What's your favorite movie?",
      "Why do you like it?",
      "What's the genre of the film?",
      "Which is more important: the plot or the special effects?",
      "Which movie has the coolest effects that you've seen?",
      "I absolutely loved that movie. It was thrilling!",
      "I thought the movie's ending was amazing.",
      "I would recommend it to anyone who likes action films.",
      "Does your school have school uniforms?",
      "What do they look like?",
      "Why do some countries require students to wear uniforms?",
      "Do you think students should wear school uniforms?",
      "What skills do good leaders have?",
      "What responsibilities does a class president have?",
      "What is the most important trait for a class president to have?",
      "Who did you vote for in the election?",
      "Why did you choose them?",
      "Did your candidate win?",
      "Do you have any pets at home?"
    ]
  },
  "BTS 32": {
    title: "Bad Habits, Being Different",
    topic: "Habits / Differences / Holidays / Stress",
    sentences: [
      "Do you know people with bad habits?",
      "Why do you think people have bad habits?",
      "How can you break a bad habit?",
      "Everyone looks a little bit different.",
      "Physical characteristics are how you look on the outside.",
      "What makes you unique and special?",
      "It's okay to be different from others.",
      "On what holidays does your school close?",
      "Why does everyone think those are important days?",
      "Which holiday is your favorite? Why?",
      "Are there any holidays you don't like?",
      "Each day, every person faces many different situations.",
      "Some situations we can control, while others we can't.",
      "What do you do when you feel stressed?",
      "I like to listen to music when I'm stressed.",
      "Exercise is a great way to reduce stress.",
      "Talking to a friend can help you feel better.",
      "It's important to take breaks when studying.",
      "Try to think positively about your situation.",
      "Don't worry. Everything will be okay."
    ]
  },
  "BTS 33": {
    title: "Games, Music, Sports, Transportation",
    topic: "Computer Games / Music / Sports / Public Transport",
    sentences: [
      "You can play games on computers, phones, and consoles.",
      "What is your favorite platform to play games on?",
      "How much time do you spend playing games?",
      "When do you like to play them?",
      "What kinds of music do you listen to?",
      "Who is your favorite recording artist?",
      "Why do you like their music?",
      "Which is better: listening to a song or watching a music video?",
      "Do you play any musical instruments?",
      "I play the piano and the guitar.",
      "Professional athletes train very hard every day.",
      "What sport would you like to play professionally?",
      "Do you take public transportation?",
      "I take the bus to school every day.",
      "The subway is faster than the bus.",
      "How do you get to school?",
      "I walk to school because it is nearby.",
      "Public transportation is good for the environment.",
      "Have you ever been to a live concert?",
      "Yes, it was an amazing experience!"
    ]
  },
  "BTS 34": {
    title: "Taking Risks, Dreams",
    topic: "Taking Risks / Possibilities / Music / Hopes and Dreams",
    sentences: [
      "Think of one person you saw with an interesting talent.",
      "Where did you see that person?",
      "What stunt did that person do?",
      "Why do you think some people do things that are dangerous?",
      "Do you listen to music from other countries?",
      "If yes, why do you like them?",
      "Do you know any traditional music from your country?",
      "How unique is Korean traditional music?",
      "What are your hopes and dreams for the future?",
      "I dream of becoming a famous scientist.",
      "My biggest dream is to travel around the world.",
      "What would you do if you could do anything?",
      "I would start my own company.",
      "Never stop dreaming and working hard.",
      "Believe in yourself and you can achieve anything.",
      "What is the biggest risk you have ever taken?",
      "Sometimes you have to take risks to succeed.",
      "I am not afraid to try new things.",
      "The future is full of possibilities.",
      "What is the most important thing in your life?"
    ]
  },
  "BTS 35": {
    title: "Global Citizenship",
    topic: "Global Issues / Environment / Future Goals / Communication",
    sentences: [
      "What does it mean to be a global citizen?",
      "A global citizen cares about the world and its people.",
      "Climate change is one of the biggest challenges we face today.",
      "What can we do to protect the environment?",
      "We can start by reducing waste and saving energy.",
      "Technology helps us connect with people from different countries.",
      "Have you ever communicated with someone from another country?",
      "Learning English opens doors to many opportunities.",
      "What global issue are you most concerned about?",
      "I am most concerned about pollution and deforestation.",
      "Education is the key to solving many world problems.",
      "Everyone deserves access to clean water and healthy food.",
      "What kind of world do you want to live in?",
      "I want to live in a peaceful and fair world.",
      "Small actions can make a big difference in the world.",
      "Volunteering is a great way to help your community.",
      "Have you ever participated in a volunteer project?",
      "Cultural diversity makes our world more interesting.",
      "We should respect and learn from different cultures.",
      "What is your goal for the future?"
    ]
  }
};

// 전체 문장 목록 (랜덤 선택용)
const ALL_SENTENCES = Object.values(BTS_SENTENCES).flatMap(level => level.sentences);

// 모듈 내보내기 (필요 시)
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { BTS_SENTENCES, ALL_SENTENCES };
}
